export const SUPPORTED_LANGUAGES = {
    en: "English",
    es: "Español",
    de: "Deutsch",
    af: "Afrikaans",
    ak: "Akan",
    am: "Amharic",
    ar: "Arabic",
    as: "Assamese",
    ay: "Aymara",
    az: "Azerbaijani",
    be: "Belarusian",
    bg: "Bulgarian",
    bho: "Bhojpuri",
    bm: "Bambara",
    bn: "Bengali",
    bs: "Bosnian",
    ca: "Catalan",
    ceb: "Cebuano",
    ckb: "Kurdish (Sorani)",
    co: "Corsican",
    cs: "Czech",
    cy: "Welsh",
    da: "Danish",
    doi: "Dogri",
    dv: "Divehi",
    ee: "Ewe",
    el: "Greek",
    eo: "Esperanto",
    et: "Estonian",
    eu: "Basque",
    fa: "Persian",
    fi: "Finnish",
    fr: "French",
    fy: "Frisian",
    ga: "Irish",
    gd: "Scottish Gaelic",
    gl: "Galician",
    gn: "Guarani",
    gom: "Konkani",
    gu: "Gujarati",
    ha: "Hausa",
    haw: "Hawaiian",
    he: "Hebrew",
    hi: "Hindi",
    hmn: "Hmong",
    hr: "Croatian",
    ht: "Haitian Creole",
    hu: "Hungarian",
    hy: "Armenian",
    id: "Indonesian",
    ig: "Igbo",
    ilo: "Iloko",
    is: "Icelandic",
    it: "Italian",
    iw: "Hebrew",
    ja: "Japanese",
    jv: "Javanese",
    jw: "Javanese",
    ka: "Georgian",
    kk: "Kazakh",
    km: "Khmer",
    kn: "Kannada",
    ko: "Korean",
    kri: "Krio",
    ku: "Kurdish",
    ky: "Kyrgyz",
    la: "Latin",
    lb: "Luxembourgish",
    lg: "Ganda",
    ln: "Lingala",
    lo: "Lao",
    lt: "Lithuanian",
    lus: "Mizo",
    lv: "Latvian",
    mai: "Maithili",
    mg: "Malagasy",
    mi: "Maori",
    mk: "Macedonian",
    ml: "Malayalam",
    mn: "Mongolian",
    mr: "Marathi",
    ms: "Malay",
    mt: "Maltese",
    my: "Burmese",
    ne: "Nepali",
    nl: "Dutch",
    no: "Norwegian",
    nso: "Northern Sotho",
    ny: "Chichewa",
    om: "Oromo",
    or: "Odia",
    pa: "Punjabi",
    pl: "Polish",
    ps: "Pashto",
    pt: "Portuguese",
    qu: "Quechua",
    ro: "Romanian",
    ru: "Russian",
    rw: "Kinyarwanda",
    sa: "Sanskrit",
    sd: "Sindhi",
    si: "Sinhala",
    sk: "Slovak",
    sl: "Slovenian",
    sm: "Samoan",
    sn: "Shona",
    so: "Somali",
    sq: "Albanian",
    sr: "Serbian",
    st: "Southern Sotho",
    su: "Sundanese",
    sv: "Swedish",
    sw: "Swahili",
    ta: "Tamil",
    te: "Telugu",
    tg: "Tajik",
    th: "Thai",
    ti: "Tigrinya",
    tk: "Turkmen",
    tl: "Tagalog",
    tr: "Turkish",
    ts: "Tsonga",
    tt: "Tatar",
    ug: "Uighur",
    uk: "Ukrainian",
    ur: "Urdu",
    uz: "Uzbek",
    vi: "Vietnamese",
    xh: "Xhosa",
    yi: "Yiddish",
    yo: "Yoruba",
    zh: "Chinese",
    zu: "Zulu"
  };
  

export const AUTO_LANGUAGE = "auto"



  